FROM evoflare.docker:50000/server

LABEL com.evoflare.product="evoflare"

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        gosu \
        dos2unix \
        curl \
&& rm -rf /var/lib/apt/lists/*

ENV ASPNETCORE_URLS http://+:5000
WORKDIR /app
EXPOSE 5000
COPY ./dist .
COPY entrypoint.sh /
RUN dos2unix /entrypoint.sh
RUN chmod +x /entrypoint.sh

HEALTHCHECK CMD curl -f http://localhost:5000 || exit 1

ENTRYPOINT ["/entrypoint.sh"]

